include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/core/l10n/messages_en.dart
    - lib/core/l10n/messages_ru.dart
    - lib/core/l10n/messages_messages.dart
    - lib/core/l10n/messages_all.dart
    - lib/app/pages/maps_page.dart
    - test/widget_test.dart
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    sized_box_for_whitespace: false
    use_key_in_widget_constructors: false
    avoid_function_literals_in_foreach_calls: false
    avoid_unnecessary_containers: false
    avoid_print: true
    prefer_single_quotes: true
    close_sinks: true
    prefer_const_literals_to_create_immutables: false